DOCID=$(shell basename $(CURDIR))
TARGET=$(DOCID).pdf
SRC=$(DOCID).tex
PDFTEX=pdflatex
BIBTEX=bibtex

.PHONY: all
all: $(TARGET)

%.pdf: %.tex
	TEXINPUTS="..:" $(PDFTEX) $<
	$(BIBTEX) $(basename $< .tex)
	TEXINPUTS="..:" $(PDFTEX) $<
	TEXINPUTS="..:" $(PDFTEX) $<

.PHONY: clean
clean:
	rm -f *.aux *.bbl *.blg *.log *.out

.PHONY: distclean
distclean: clean
	rm -f $(TARGET)
